apiVersion: v1
kind: Service
metadata:
  name: votingapp
  namespace: votingapp
spec:
  type: LoadBalancer
  selector:
    app: votingapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080